-- Fix site_content table schema to support JSON content
-- Run this in your Supabase SQL Editor

CREATE TABLE IF NOT EXISTS site_content (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    content JSONB DEFAULT '{}'::JSONB,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_by UUID
);

-- Ensure the content column exists if table was already created
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'site_content' AND column_name = 'content') THEN
        ALTER TABLE site_content ADD COLUMN content JSONB DEFAULT '{}'::JSONB;
    END IF;
END $$;

-- Enable unauthenticated access (since we disabled auth)
ALTER TABLE site_content DISABLE ROW LEVEL SECURITY;

-- Insert a default row if table is empty to ensure ID 1 exists (optional but helpful for singleton)
INSERT INTO site_content (id, content)
SELECT 1, '{}'::JSONB
WHERE NOT EXISTS (SELECT 1 FROM site_content WHERE id = 1);
